//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int IssueId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> Stdid { get; set; }
        public Nullable<int> Bookid { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual student student { get; set; }
    }
}
